/**
 * Copyright 2017 Netflix, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.netflix.florida.startup;

import com.google.inject.Injector;
import com.netflix.archaius.guice.ArchaiusModule;
import com.netflix.governator.InjectorBuilder;
import com.netflix.governator.guice.jetty.Archaius2JettyModule;
import com.netflix.governator.guice.servlet.WebApplicationInitializer;

/**
 * The "main" class that boots up the service. When it's deployed within a servlet container such
 * as Tomcat, only the createInjector() is called. For local testing one simply invokes the
 * main() method as if running a normal Java app.
 *
 * @author This file is auto-generated by runtime@netflix.com. Feel free to modify.
 */
public class Florida implements WebApplicationInitializer {

    public static void main(String[] args) throws Exception {
        InjectorBuilder.fromModules(
                new FloridaModule(),
                new Archaius2JettyModule(),
                new ArchaiusModule() {
                    @Override
                    protected void configureArchaius() {
                        bindApplicationConfigurationOverrideResource("laptop");
                    }
                }).createInjector().awaitTermination();
    }

    @Override
    public Injector createInjector() {
        return InjectorBuilder.fromModules(new FloridaModule()).createInjector();
    }
}
