#!/bin/bash
# chkconfig: 2345 95 20
# description: This script does some stuff
# processname: dynomite

start() {
   echo "starting dynomite... "
   cd /apps/dynomite/bin/
   /apps/dynomite/bin/dynomite -d -c /apps/dynomite/conf/dynomite.yml -m16384 -M200000 --output=/logs/system/dynomite/dynomite.log &
}

stop() {
   echo "stop"
   PID=`pgrep dynomite`
   if [[ "" !=  "$PID" ]]; then
      echo "killing $PID"
      kill -9 $PID
   fi
}

case "$1" in start)
  start
;;
  stop)
  stop
;;
*)

echo $"Usage: $0 {start|stop}"
RETVAL=1
esac
exit 0





